accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout')
]

blogs/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from django.conf import settings

app_name = 'post'

urlpatterns = [
    path('post_key/<int:pk>/',views.MovieDetailView.as_view(),name='detail_pk'),
    url(r'^post/(?P<tag_slug>[-\w]+)/$',views.MovieList.as_view(),name='list_slug'),
    path('',views.MovieList.as_view(),name='list'),
    url(r'post_key/(?P<movie_id>[\d]+)/comment/$',views.CreateCommentView.as_view(),name='CreateComment'),
    url(r'post_key/(?P<movie_id>[\d]+)/comment/(?P<pk>[\d]+)/$',views.UpdateCommentView.as_view(),name='UpdateComment'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

moviereviews/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('account/',include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.

class Post(models.Model):
    POST_STATUS     ={('A','ACTIVE'),('D',"INACTIVE"),}
    title           = models.CharField(max_length=200)
    image           = models.ImageField(default='default.png',blank=True)
    slug            = models.SlugField(unique=True)
    description     = models.TextField(blank=True,default='')
    release_date    = models.DateTimeField(blank=True)
    language        = models.CharField(default='', max_length=100)
    created_date    = models.DateTimeField(auto_now_add=True)
    updated_date    = models.DateTimeField(auto_now=True)
    status          = models.CharField(default='A', max_length=50,choices=POST_STATUS)
    tags            = TaggableManager()
    

    def __str__(self):
        return self.title
    
    def TruncateStringTo50(self):
        return self.description[0:80]+"..."	
        
    def get_absolute_url(self):
        return reverse('post:detail_pk',kwargs={'pk':self.pk})

    class Meta:
        ordering = ('-created_date',)


class CommentManager(models.Manager):
    def get_comment_or_empty_comment_form(self,post,user):
        try:
            return Comment.objects.get(post_obj=post,user_obj=user)
        except Comment.DoesNotExist:
            return Comment.setComment(post_obj=post,user_obj=user)


class Comment(models.Model):
    post_obj        = models.ForeignKey(Post, related_name="post_comment", on_delete=models.CASCADE)
    user_obj        = models.ForeignKey(User,related_name='user_comment', on_delete=models.CASCADE)
    comment_title   = models.CharField(max_length=255)
    ratings         = models.PositiveIntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(5)])
    body            = models.TextField(default='')
    created_date    = models.DateTimeField( auto_now_add=True)
    updated_date    = models.DateTimeField(auto_now=True)
    comment_status  = models.BooleanField(default=True)
    objects         = CommentManager()
    
    @classmethod
    def setComment(self, post_obj,user_obj):
        return self(post_obj=post_obj, user_obj=user_obj)

    class Meta:
        ordering = ['-updated_date','-ratings']
        unique_together = ('post_obj','user_obj')
	
    def __str__(self):
        return 'Comment by {} on {}'.format(self.comment_title, self.post_obj)

blogs/forms.py
from  django import forms
from . import models
from django.contrib.auth.models import User


class create_post(forms.ModelForm):
	class Meta:
		model=models.Post
		fields=['title','slug','description','release_date','language','tags','image']

class create_comment(forms.ModelForm):
	post_obj=forms.ModelChoiceField(
		widget=forms.HiddenInput,
		disabled=True,
		queryset=models.Post.objects.all()
	)
	user_obj=forms.ModelChoiceField(
		widget=forms.HiddenInput,
		disabled=True,
		queryset=User.objects.all()
	)
	class Meta:
		model = models.Comment
		fields = ['post_obj','user_obj','comment_title','ratings','body']

blogs/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from django.db.models import Count 
from taggit.models import Tag
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import create_comment
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from . import models


class MovieList(ListView):
    paginate_by=3
    model = models.Post

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        tag=None
        tag=self.kwargs.get('tag_slug')
        if tag:
            tag=get_object_or_404(Tag,slug=tag)
            context['post_list']=self.model.objects.filter(tags__in=[tag])
        else:
            context['post_list']= self.model.objects.all()

        ############## Pagination block 
        paginating=Paginator(context['post_list'],3)
        page=self.request.GET.get('page')
        try:
            context['post_list']=paginating.page(page)
        except PageNotAnInteger:
            context['post_list']=paginating.page(1)
        except EmptyPage:
            context['post_list']=paginating.page(paginating.num_pages)
        ############################
        return context



class MovieDetailView(DetailView):
    model = models.Post

    def get_object(self):
        pk=self.kwargs.get('pk')
        return get_object_or_404(models.Post,id=pk)

   
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        post_Info=get_object_or_404(models.Post,id=self.kwargs.get('pk'))
        context['comments']=post_Info.post_comment.all().filter(comment_status=True)
        #context['comment_added']=
        
        post_tag_related_id=post_Info.tags.values_list('id',flat=True)
        related_blogs=self.model.objects.filter(tags__in=post_tag_related_id).exclude(id=post_Info.pk)
        related_blogs=related_blogs.annotate(same_count=Count('tags')).order_by('-same_count','-created_date')
        context['related_blogs']=related_blogs

        if self.request.user.is_authenticated:
            commentFormInfo = models.Comment.objects.get_comment_or_empty_comment_form(
                post=post_Info,
                user=self.request.user)
            if commentFormInfo.id:
                comment_form_url = reverse(
                    'post:UpdateComment',
                    kwargs={
                        'movie_id': commentFormInfo.post_obj.id,
                        'pk': commentFormInfo.id
                        })
            else:
                comment_form_url = reverse(
                        'post:CreateComment',
                        kwargs={
                            'movie_id': self.object.id,
                            }
                    )
            
            comment_form = create_comment(instance=commentFormInfo)
            context['comment_form'] = comment_form
            context['comment_form_url'] = comment_form_url
        return context


class CreateCommentView(LoginRequiredMixin,CreateView):
    form_class=create_comment

    def get_initial(self):
         initial=super().get_initial()
         initial['user_obj']=self.request.user.id
         initial['post_obj']=self.kwargs['movie_id']
         return initial

    def render_to_response(self,context,**kwargs):
        # import pdb
        # pdb.set_trace()
        movie_id=int(context['form']['post_obj'].value().__str__())
        movie_detail_url=reverse('post:detail_pk', kwargs={'pk':movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.object.post_obj.id 
        return reverse('post:detail_pk', kwargs={'pk':movie_id})


class UpdateCommentView(LoginRequiredMixin,UpdateView):
    form_class=create_comment
    queryset = models.Comment.objects.all()

    def get_object(self,Queryset=None):
        CommentInfo=super().get_object(Queryset)
        if CommentInfo.user_obj!=self.request.user:
            raise PermissionDenied("cannot modify other user's comment")
        return CommentInfo

    def render_to_response(self,context,**kwargs):
        print(context)
        movie_id=context['object'].id 
        movie_detail_url=reverse('post:detail_pk',kwargs={'pk':movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id=self.object.post_obj.id
        return reverse('post:detail_pk',kwargs={'pk':movie_id})

blogs/templates/blogs/latest_posts.html
<ul>
{%for latest in latest_posts%}
<li>
    <a href="{{latest.get_absolute_url}}">{{latest.title}}</a>
</li>
{%endfor%}
</ul>

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load static %}
{%load custom_tags%}

<!-- css -->
{%block style%}
<link rel="stylesheet" href="{%static 'blogs/css/style.css'%}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
{%endblock style%}

<!-- head block  -->

{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
{% endblock %}

<!-- title  block -->

{% block title %}
    {{post.title}}
{% endblock %}

<!-- end of title block -->


{%  block content %}

<div class="col-12">
	<!-- movie detail -->
<div>
	
		<p class="display-5 arrow-circle-left"><a href="{% url 'post:list'%}"><i class="fas fa-arrow-circle-left"></i></a> </p>
	
		<p class='display-1 text-center'>{{post.title}}</p>
		<div class="row">
			<img src="{{post.image.url}}" alt="" class="col-10 col-sm-6 col-md-4 img-fluid height:auto">
			<div class="col-12 col-md-8 col-sm-6">
				<p class="lead">{{post.description}}</p>
				<p class="font-italic">Release date: {{post.release_date}}</p> 
			</div>       
		</div>
		
	</div>
	<!-- end of movie detail block -->
	
	<hr>
	
	<!-- average star rating -->
	<div class="bg-dark">
			{%AVERAGE_RATINGS post.pk as AVERAGE%}
			<p class="text-white font-weight-bold pl-2 pt-1  inline">{%if AVERAGE.avg_rating%}{{AVERAGE.avg_rating}}
			{%else%}0{%endif%}</p>
			<input type="hidden" id="myVar" name="variable" value="{%if AVERAGE.avg_rating%}{{AVERAGE.avg_rating}}{%else%}0{%endif%}">
			<div class="inline">
				<div class="stars-outer">
					<div class="stars-inner"></div>
				</div>
			</div>
			
				<span class="number-rating"></span>
	</div>
	<!-- end of average star rating -->
	
	<hr>
	
	<!-- comment section -->
	
		<!-- comment count -->
		<p><span class="badge badge-pill badge-light">{{comments.count}} comment{{comments.count|pluralize}}</span> </p>
	
	
	
	
	
	
		<!-- comment list -->
		<input type="hidden" id="commentsCount" name="variable" value="{{comments}}">
		<script>
			commentRating=[];
			commentRatingPk=[];
		</script>
		{%for commentInfo in comments%}
		<div class="col-12 border bg-light mb-1">
			{{commentInfo.pk}}
			
			
			<div class="bg-dark text-light">
				<h4 class="text-monospace">{{commentInfo.comment_title}}  <span class="badge badge-pill badge-warning">(Ratings:{{commentInfo.ratings}})</span></h4>
				<!-- javascript pass -->
				<input type="hidden" id="userCommentRatingValue" name="variable" value="{{commentInfo.ratings}}">
				<input type="hidden" id="userCommentRatingPK" name="variable" value="{{commentInfo.user_obj}}">
			
			<div class='{{commentInfo.user_obj}}'>
				<div class="stars-outer">
					<div class="stars-inner"></div>
				</div>
			</div>
			</div>
	
			<p class="lead">{{commentInfo.body|linebreaks}}</p>
			<p>
				comment {{forloop.count}} by <span class="badge badge-pill badge-dark">{{commentInfo.user_obj}}</span> <span class="font-italic">dated:{{commentInfo.updated_date}}</span>  
			</p>
		</div>
	
	
	
		<script>
			value={{commentInfo.ratings}};
			pk="{{commentInfo.user_obj}}";
			pk=pk.toString();
			commentRating.push(value);
			commentRatingPk.push(pk);
			
		</script>
	
	
	
		{%endfor%}
	
	
	
		<script>
			// console.log(d)
		</script>
		<input type="hidden" id='jspass' name='variable' value=`${d}%`>
	
	
	
		{%if comments.empty%}
		<p>There are no comments yet.</p>
		{%endif%}
	
		{% if comment_added %}
		<h3>Your comment has been added.</h3>
		{%endif%}
	
	<hr>
	{%if comment_form%}
		<div>
		<h2>Add a new comment</h2>
		<form method="post" action="{{comment_form_url}}">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Add Comment"></p>
		</form>
		</div>
	{%else%}
		<div class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>Hey! </strong>
			<a href="{% url 'accounts:login' %}">Login</a> or 
			<a href="{% url 'accounts:signup' %}">Signup</a>  
			to review this movie :)
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		  </div>
		
	{%endif%}
	<hr>
	
	<!-- Related post -->
	
	<div class="related_post">
		<h2>
			SIMILAR POSTS
		</h2>
		{%if similar_blog not in related_blogs%}
			There are no similar posts yet.
		{%endif%}
	
		{%for similar_blog in related_blogs%}
	
		<div class="card" style="width: 18rem;">
				<div class="card-body">
				  <h5 class="card-title"><a href="{{similar_blog.get_absolute_url }}">{{similar_blog.title}}</a></h5>
				  <h6 class="card-subtitle mb-2 text-muted">{{similar_blog.ratings}}</h6>
				  <p class="card-text">{{similar_blog.description|truncatewords:17}}</p>
					  {%for tagInfo in similar_blog.tags.all%}
					<a href="{%url 'post:list_slug' tag_slug=tagInfo.slug %}">{{tagInfo.name}}</a>
					{%endfor%}
				</div>
			  </div>
			  
		{%endfor%}
	</div>
	
	<!-- end of related post -->

</div>

{% endblock %}

{%block script%}
<script src="{%static 'blogs/js/script_details.js'%}"></script>
{%endblock script%}

blogs/templates/blogs/post_list.html
{% extends 'base.html'%}
{% load static%}
{%load custom_tags%}

{% block title %}Movie Reviews{% endblock %}

{% block content %}

    <div class='row'>
    {% for post in post_list %}
        <div class="col-12 col-lg-6 col-xl-4 mt-4 border">
            <h3 class="text-center text-justify"><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
            <img src="{{post.image.url}}" alt="article image" class="rounded mx-auto d-block img-fluid max-width:100% height:auto" >
            <p class="text-center text-justify">Release Date: {{post.release_date}}</p>
            {%AVERAGE_RATINGS post.pk as AVERAGE%}
            
            <p class='text-center'>Ratings:
                {%if AVERAGE.avg_rating%}{{AVERAGE.avg_rating}}
                {%else%}0{%endif%}</p>
                <input type="hidden" id="myVar" name="variable" value="{{ AVERAGE.avg_rating}}">
            <p class="text-center">Genre: 
                    {% for tag in post.tags.all %}
                    <a href="{% url 'post:list_slug' tag_slug=tag.slug %}">
                    {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
            </p>
            <!--  -->
        </div>

        {%empty%}
            <p>No Movies Post yet!</p>
    {% endfor %}
    </div>

    {%include 'pagination.html' with page=page_obj%}
{% endblock %}
{%block script%}
<script src="{%static 'blogs/js/script.js'%}"></script>
{%endblock script%}

blogs/templates/blogs/recently_commented_posts.html
<h3>Recently Commented Posts</h3>
<ul>
    {%for posts in recent%}
        <li>
            <a href="{%url 'post:detail_pk' pk=posts.post_obj.id %}">{{posts.post_obj}}</a>
        </li>
    {%endfor%}
</ul>