accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout')
]

blogs/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from django.conf import settings

app_name = 'post'

urlpatterns = [
    path('post_key/<int:pk>/',views.MovieDetailView.as_view(),name='detail_pk'),
    url(r'^post/(?P<tag_slug>[-\w]+)/$',views.MovieList.as_view(),name='list_slug'),
    path('',views.MovieList.as_view(),name='list'),
    url(r'post_key/(?P<movie_id>[\d]+)/comment/$',views.CreateCommentView.as_view(),name='CreateComment'),
    url(r'post_key/(?P<movie_id>[\d]+)/comment/(?P<pk>[\d]+)/$',views.UpdateCommentView.as_view(),name='UpdateComment'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

moviereviews/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('account/',include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{%load custom_tags%}
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% block style %}{% endblock style%}

    <title> {% block title %} {% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'post:list'%}">MovZap</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Heyy!! {{user.username|title}}</a>
                </li>
                
                  <!-- <a class="nav-link" href="{% url 'accounts:logout'%}">logout<span class="sr-only">(current)</span></a> -->
                
                
                <li class="nav-item active">
                <form action="{% url 'accounts:logout'%}" method="POST">
                  {% csrf_token %}
                  <button class="btn btn-outline-success my-2 mr-0 my-sm-0 " type="submit">Logout</button>
                </form>
                </li>
              {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:signup'%}"><button type="button" class="btn btn-outline-primary">SignUp</button><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:login' %}"><button type="button" class="btn btn-outline-secondary">Login</button><span class="sr-only">(current)</span></a>
                </li>
              {% endif %}
              

              
              

              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li> -->
              

            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
      </nav>
    
    <div class="container">
        <div class='row'>

          <div class="col-12 col-lg-9">
          {% block content %}
          <h1>Hello, world!</h1>
          {% endblock %}
          </div>

          <div class="col-0 col-lg-3 alert alert-warning  my-4" role="alert"> 
          {% block sidebar %}
            <p>Added {% TotalPosts %} Movies so far.</p>
            <h3>Latest posts</h3>
            {% most_recent_added_movies %}
            <br>
            {%if user.is_authenticated%}
            {%recently_commented user.id%}
            {%endif%}
          {%endblock%}
          </div>

        </div>  
    </div>
    <footer>
      
    </footer>	
    <!-- Optional JavaScript -->
    {%block script%}{%endblock script%}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>